// Code generated by protoc-gen-go.
// source: entry.proto
// DO NOT EDIT!

/*
Package golobo is a generated protocol buffer package.

It is generated from these files:
	entry.proto

It has these top-level messages:
	Target
*/
package golobo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Target struct {
	Ip      string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Rpc     int64  `protobuf:"varint,2,opt,name=rpc" json:"rpc,omitempty"`
	Tunnel  int64  `protobuf:"varint,3,opt,name=tunnel" json:"tunnel,omitempty"`
	Service string `protobuf:"bytes,4,opt,name=service" json:"service,omitempty"`
	Version string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Target) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Target) GetRpc() int64 {
	if m != nil {
		return m.Rpc
	}
	return 0
}

func (m *Target) GetTunnel() int64 {
	if m != nil {
		return m.Tunnel
	}
	return 0
}

func (m *Target) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Target) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Target)(nil), "golobo.Target")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2b, 0x29,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcf, 0xcf, 0xc9, 0x4f, 0xca, 0x57,
	0x2a, 0xe3, 0x62, 0x0b, 0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x2c, 0x90,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x2c, 0x10, 0x12, 0xe0, 0x62, 0x2e, 0x2a, 0x48,
	0x96, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x85, 0xc4, 0xb8, 0xd8, 0x4a, 0x4a, 0xf3,
	0xf2, 0x52, 0x73, 0x24, 0x98, 0xc1, 0x82, 0x50, 0x9e, 0x90, 0x04, 0x17, 0x7b, 0x71, 0x6a, 0x51,
	0x59, 0x66, 0x72, 0xaa, 0x04, 0x0b, 0x58, 0x3b, 0x8c, 0x0b, 0x92, 0x29, 0x4b, 0x2d, 0x2a, 0xce,
	0xcc, 0xcf, 0x93, 0x60, 0x85, 0xc8, 0x40, 0xb9, 0x49, 0x6c, 0x60, 0x67, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x40, 0xd2, 0xca, 0x5b, 0x95, 0x00, 0x00, 0x00,
}
